# -*- coding: utf-8 -*-
# Problem 45
# Triangular, pentagonal, and hexagonal

# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:

# Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
# Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
# Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

from time import time
from UsefulFunctions import triangle_num_gen, pentagonal_num_gen, hexagonal_num_gen

start_time = time()

tgen = triangle_num_gen()
for i in range(286):        # get the next triangle ready
    t = next(tgen)

pgen = pentagonal_num_gen()
for i in range(165):
    p = next(pgen)

hgen = hexagonal_num_gen()
for i in range(143):
    h = next(hgen)

# print t, p, h
while True:
    while p < t:
        p = next(pgen)
    while h < t:
        h = next(hgen)
    if t == p == h:
        break

    t = next(tgen)

print t

print "Total Time: ", time() - start_time

# Completed on Wed, 5 Mar 2014, 05:28
# Solve by: 36162
# ---------------
# 1533776805
# Total Time:  0.0769999027252
# [Finished in 0.3s]

# Next number: 57722156241751
